library(tidyverse)
library(questionr)
library(nycflights23)
library(FactoMineR)
library(factoextra)
library(nnet)
library(plm)
library(lme4)

data("hdv2003")
data("rp2012")
data("flights")
data("airports")
data("airlines")
data("economics")